name: Build and Deploy Angular Project

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 65002
        script: |
          cd domains/anthonygt.website/anthonygt
          git pull
          wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.39.0/install.sh | bash
          source ~/.profile
          nvm ls-remote
          nvm install 16.17.0
          node -v
          yes no | npm run build
          cp -rf dist/anthonygth/* ../public_html/
          rm -rf dist


    - name: Clean up
      run: rm -rf dist

